import 'recipe.dart';

final List<Recipe> mockRecipes = [
  const Recipe(
    id: 'curated-1',
    dishName: 'Paneer Butter Masala',
    description: 'A rich, creamy, and mildly sweet North Indian curry made with cottage cheese in tomato-butter gravy.',
    cuisine: 'North Indian',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    totalTimeMinutes: 40,
    servings: 2,
    difficulty: 'Medium',
    spiceLevel: 'Mild',
    ingredients: [
      RecipeIngredient(name: 'Paneer (Cubes)', quantity: 200, unit: 'g'),
      RecipeIngredient(name: 'Ripe Tomatoes', quantity: 4, unit: 'piece'),
      RecipeIngredient(name: 'Butter', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Fresh Cream', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Ginger-Garlic Paste', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Kasuri Methi', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Garam Masala', quantity: 0.5, unit: 'tsp'),
      RecipeIngredient(name: 'Kashmiri Red Chilli Powder', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Kadhai or Pan', 'Blender'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Roughly chop tomatoes and blend into a smooth puree.'),
      RecipeStep(stepNumber: 2, instruction: 'Melt butter in a kadhai on medium heat, add ginger-garlic paste and sauté for 1 minute.'),
      RecipeStep(stepNumber: 3, instruction: 'Add tomato puree, Kashmiri chilli powder, and salt. Cook until butter separates.'),
      RecipeStep(stepNumber: 4, instruction: 'Add paneer cubes and simmer gently for 4 minutes with cream and crushed kasuri methi.'),
    ],
    costEstimateInr: 160.0,
    nutrition: NutritionInfo(calories: 380, proteinG: 14.5, carbsG: 12.0, fatG: 30.0, fiberG: 3.2),
    dietaryTags: ['Vegetarian', 'High Protein'],
    allergyWarnings: ['Contains Dairy'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-2',
    dishName: 'South Indian Tomato Rasam',
    description: 'Tangy and comforting pepper-cumin soup infused with tempered curry leaves and crushed garlic.',
    cuisine: 'South Indian',
    mealCategory: 'Lunch',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 3,
    difficulty: 'Easy',
    spiceLevel: 'Spicy',
    ingredients: [
      RecipeIngredient(name: 'Tomatoes', quantity: 3, unit: 'piece'),
      RecipeIngredient(name: 'Tamarind Pulp', quantity: 1, unit: 'tbsp'),
      RecipeIngredient(name: 'Black Pepper & Cumin powder', quantity: 1.5, unit: 'tsp'),
      RecipeIngredient(name: 'Garlic cloves', quantity: 4, unit: 'piece'),
      RecipeIngredient(name: 'Mustard seeds & Curry leaves', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Ghee or Oil', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Rasam pot / saucepan'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Mash boiled tomatoes with tamarind water, turmeric, and salt.'),
      RecipeStep(stepNumber: 2, instruction: 'Simmer the broth until froth forms on top.'),
      RecipeStep(stepNumber: 3, instruction: 'Temper mustard, curry leaves, and crushed garlic in ghee, then pour over the rasam.'),
    ],
    costEstimateInr: 45.0,
    nutrition: NutritionInfo(calories: 65, proteinG: 1.8, carbsG: 9.0, fatG: 2.5, fiberG: 2.0),
    dietaryTags: ['Vegetarian', 'Vegan Option', 'Immunity Booster'],
    allergyWarnings: [],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-3',
    dishName: 'Poha (Kanda Batata Poha)',
    description: 'Popular Maharashtrian breakfast made of flattened rice tempered with mustard, peanuts, and turmeric.',
    cuisine: 'Maharashtrian',
    mealCategory: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    totalTimeMinutes: 20,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Thick Poha (Flattened Rice)', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Onion (finely chopped)', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Potato (cubed small)', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Roasted Peanuts', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Green Chillies & Curry Leaves', quantity: 2, unit: 'piece'),
      RecipeIngredient(name: 'Lemon Juice', quantity: 1, unit: 'tbsp'),
    ],
    equipment: ['Pan', 'Strainer/Colander'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Rinse poha in a colander and drain completely with a pinch of turmeric and salt.'),
      RecipeStep(stepNumber: 2, instruction: 'Heat oil, fry peanuts and potatoes until tender. Add onions and green chillies.'),
      RecipeStep(stepNumber: 3, instruction: 'Fold in the softened poha, cover and steam on low for 2 minutes. Garnish with lemon juice.'),
    ],
    costEstimateInr: 50.0,
    nutrition: NutritionInfo(calories: 220, proteinG: 5.5, carbsG: 38.0, fatG: 6.0, fiberG: 3.5),
    dietaryTags: ['Vegetarian', 'Vegan', 'Quick Meals', 'Under 20 Mins'],
    allergyWarnings: ['Contains Peanuts'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-4',
    dishName: 'Soya & Paneer Protein Bhurji',
    description: 'High-protein scrambled cottage cheese and minced soya chunks tossed with onions, capsicum, and aromatic Indian spices.',
    cuisine: 'North Indian',
    mealCategory: 'Lunch',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Paneer (crumbled)', quantity: 150, unit: 'g'),
      RecipeIngredient(name: 'Soya Granules (soaked)', quantity: 50, unit: 'g'),
      RecipeIngredient(name: 'Onion & Green Bell Pepper', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Ginger & Garlic Paste', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Garam Masala & Turmeric', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Mustard Oil / Ghee', quantity: 1, unit: 'tbsp'),
    ],
    equipment: ['Kadhai / Skillet'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Squeeze water from soaked soya granules completely.'),
      RecipeStep(stepNumber: 2, instruction: 'Heat ghee in a pan, sauté ginger-garlic, onions, and bell pepper until golden.'),
      RecipeStep(stepNumber: 3, instruction: 'Add spices, followed by soya granules and crumbled paneer. Toss vigorously for 4 minutes.'),
    ],
    costEstimateInr: 95.0,
    nutrition: NutritionInfo(calories: 310, proteinG: 23.5, carbsG: 8.0, fatG: 18.0, fiberG: 4.5),
    dietaryTags: ['High-Protein', 'Vegetarian', 'High Protein', 'Keto Friendly'],
    allergyWarnings: ['Contains Dairy', 'Contains Soy'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-5',
    dishName: 'Palak & Moong Sprouts Khichdi',
    description: 'Wholesome, low-calorie, nutrient-dense pot meal of yellow moong dal, sprouted beans, and spinach puree tempered with cumin.',
    cuisine: 'Healthy Meals',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 18,
    totalTimeMinutes: 28,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Mild',
    ingredients: [
      RecipeIngredient(name: 'Moong Dal & Brown Rice', quantity: 0.75, unit: 'cup'),
      RecipeIngredient(name: 'Fresh Spinach Puree', quantity: 1, unit: 'cup'),
      RecipeIngredient(name: 'Moong Sprouts', quantity: 0.5, unit: 'cup'),
      RecipeIngredient(name: 'Cumin seeds & Asafoetida', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Ghee', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Pressure Cooker / Pot'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Pressure cook moong dal, sprouts, and brown rice with turmeric and salt for 3 whistles.'),
      RecipeStep(stepNumber: 2, instruction: 'Stir in fresh spinach puree and simmer for 3 minutes until vibrant green.'),
      RecipeStep(stepNumber: 3, instruction: 'Temper with a dash of cumin seeds in ghee and serve hot with low-fat curd.'),
    ],
    costEstimateInr: 65.0,
    nutrition: NutritionInfo(calories: 240, proteinG: 12.0, carbsG: 38.0, fatG: 4.5, fiberG: 7.0),
    dietaryTags: ['Healthy Meals', 'Vegetarian', 'Low Calorie', 'High Fiber', 'Gluten Free'],
    allergyWarnings: [],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-6',
    dishName: 'Gulab Jamun with Saffron Syrup',
    description: 'Melt-in-mouth golden khoya dumplings fried gently in pure ghee and soaked in warm cardamom-saffron sugar syrup.',
    cuisine: 'Desserts',
    mealCategory: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    totalTimeMinutes: 35,
    servings: 4,
    difficulty: 'Medium',
    spiceLevel: 'Sweet',
    ingredients: [
      RecipeIngredient(name: 'Mawa / Khoya', quantity: 200, unit: 'g'),
      RecipeIngredient(name: 'Paneer (finely grated)', quantity: 50, unit: 'g'),
      RecipeIngredient(name: 'Maida', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Sugar (for syrup)', quantity: 1.5, unit: 'cup'),
      RecipeIngredient(name: 'Cardamom pods & Saffron strands', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Ghee (for frying)', quantity: 2, unit: 'cup'),
    ],
    equipment: ['Deep Kadhai', 'Saucepan'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Boil sugar with water, crushed cardamom, and saffron to form a single-string warm syrup.'),
      RecipeStep(stepNumber: 2, instruction: 'Knead mawa, paneer, and maida into a smooth crack-free dough. Roll into small smooth spheres.'),
      RecipeStep(stepNumber: 3, instruction: 'Deep fry in medium-low ghee until golden brown. Drop immediately into warm sugar syrup for 30 mins.'),
    ],
    costEstimateInr: 120.0,
    nutrition: NutritionInfo(calories: 320, proteinG: 6.0, carbsG: 45.0, fatG: 14.0, fiberG: 0.5),
    dietaryTags: ['Desserts', 'Vegetarian', 'Dessert', 'Indian Mithai'],
    allergyWarnings: ['Contains Dairy', 'Contains Gluten'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-7',
    dishName: 'Mumbai Pav Bhaji',
    description: 'Iconic street food favorite — spiced mashed vegetable curry loaded with butter, served with toasted buttery pav buns and onions.',
    cuisine: 'Street Food',
    mealCategory: 'Snacks',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Boiled Potatoes, Peas & Cauliflower', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Tomatoes & Onions (chopped)', quantity: 2, unit: 'piece'),
      RecipeIngredient(name: 'Pav Bhaji Masala', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Kashmiri Chilli Powder', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Salted Butter', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Fresh Pav Buns', quantity: 4, unit: 'piece'),
    ],
    equipment: ['Tawa / Flat Pan', 'Potato Masher'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Heat generous butter on tawa, sauté onions, capsicum, and ginger-garlic paste.'),
      RecipeStep(stepNumber: 2, instruction: 'Add tomatoes, boiled vegetables, and pav bhaji masala. Vigorously mash with potato masher adding water.'),
      RecipeStep(stepNumber: 3, instruction: 'Simmer until glossy and rich. Toast pav buns on the same buttered tawa and serve with lemon wedges.'),
    ],
    costEstimateInr: 85.0,
    nutrition: NutritionInfo(calories: 420, proteinG: 8.5, carbsG: 55.0, fatG: 19.0, fiberG: 6.0),
    dietaryTags: ['Street Food', 'Vegetarian', 'Snacks', 'Popular Street Food'],
    allergyWarnings: ['Contains Dairy', 'Contains Gluten'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-8',
    dishName: 'Crispy Masala Dosa',
    description: 'Golden fermented rice-lentil crepe filled with spiced tempered potato masala, served with coconut chutney.',
    cuisine: 'South Indian',
    mealCategory: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'Medium',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Dosa Batter', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Boiled Potatoes (mashed)', quantity: 2, unit: 'piece'),
      RecipeIngredient(name: 'Mustard seeds & Curry leaves', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Onions & Green chillies', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Ghee or Oil', quantity: 2, unit: 'tbsp'),
    ],
    equipment: ['Cast Iron Tawa'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Temper mustard, curry leaves, and green chillies in oil; add sliced onions and turmeric.'),
      RecipeStep(stepNumber: 2, instruction: 'Fold in mashed potatoes and salt to prepare the potato masala filling.'),
      RecipeStep(stepNumber: 3, instruction: 'Spread dosa batter on hot tawa in concentric circles. Drizzle ghee, crisp until golden, add filling and roll.'),
    ],
    costEstimateInr: 60.0,
    nutrition: NutritionInfo(calories: 280, proteinG: 6.5, carbsG: 46.0, fatG: 8.0, fiberG: 3.5),
    dietaryTags: ['South Indian', 'Vegetarian', 'Vegan Option'],
    allergyWarnings: [],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-9',
    dishName: 'Paneer Tikka Naan Pizza',
    description: 'Fusion delight featuring fluffy tandoori naan as crust, topped with spiced makhani sauce, marinated paneer tikka, and gooey mozzarella.',
    cuisine: 'Italian Fusion',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 12,
    cookTimeMinutes: 12,
    totalTimeMinutes: 24,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Garlic Naan (baked/ready)', quantity: 2, unit: 'piece'),
      RecipeIngredient(name: 'Paneer Tikka cubes', quantity: 120, unit: 'g'),
      RecipeIngredient(name: 'Tikka/Makhani Pizza Sauce', quantity: 4, unit: 'tbsp'),
      RecipeIngredient(name: 'Mozzarella Cheese (shredded)', quantity: 1, unit: 'cup'),
      RecipeIngredient(name: 'Capsicum & Red Onion rings', quantity: 0.5, unit: 'cup'),
      RecipeIngredient(name: 'Oregano & Chaat Masala', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Oven / Tawa with lid'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Spread makhani sauce evenly over the warm garlic naan.'),
      RecipeStep(stepNumber: 2, instruction: 'Layer with mozzarella cheese, paneer tikka cubes, capsicum, and onions.'),
      RecipeStep(stepNumber: 3, instruction: 'Bake at 200°C for 8 minutes (or cover on tawa on low heat) until cheese bubbles and crust turns crispy.'),
    ],
    costEstimateInr: 140.0,
    nutrition: NutritionInfo(calories: 390, proteinG: 16.5, carbsG: 38.0, fatG: 20.0, fiberG: 2.8),
    dietaryTags: ['Italian Fusion', 'Vegetarian', 'High Protein', 'Fusion'],
    allergyWarnings: ['Contains Dairy', 'Contains Gluten'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-10',
    dishName: 'Veg Manchurian in Hot Garlic Sauce',
    description: 'Crispy minced cabbage-carrot dumplings simmered in dark, spicy, tangy soy-garlic Indo-Chinese gravy.',
    cuisine: 'Indo-Chinese',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    totalTimeMinutes: 30,
    servings: 2,
    difficulty: 'Medium',
    spiceLevel: 'Spicy',
    ingredients: [
      RecipeIngredient(name: 'Finely chopped Cabbage & Carrots', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Cornflour & All-purpose flour', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Minced Garlic & Ginger', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Dark Soy Sauce & Vinegar', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Red Chilli Sauce', quantity: 1.5, unit: 'tbsp'),
      RecipeIngredient(name: 'Spring Onions', quantity: 0.5, unit: 'cup'),
    ],
    equipment: ['Kadhai / Wok'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Mix vegetables with cornflour and pepper. Form into balls and fry until crispy golden.'),
      RecipeStep(stepNumber: 2, instruction: 'In a wok, stir-fry garlic, ginger, and green chillies on high heat. Add sauces and vegetable broth.'),
      RecipeStep(stepNumber: 3, instruction: 'Add cornflour slurry to thicken the gravy, drop the crispy manchurian balls, toss for 1 minute and serve.'),
    ],
    costEstimateInr: 90.0,
    nutrition: NutritionInfo(calories: 275, proteinG: 5.5, carbsG: 35.0, fatG: 12.0, fiberG: 4.2),
    dietaryTags: ['Indo-Chinese', 'Vegetarian', 'Vegan Option'],
    allergyWarnings: ['Contains Soy', 'Contains Gluten'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-11',
    dishName: 'Hyderabadi Dum Veg Biryani',
    description: 'Royal aromatic Basmati rice layered with saffron, mint, fried onions, and spiced seasonal vegetables slow-cooked under dum.',
    cuisine: 'North Indian',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    totalTimeMinutes: 45,
    servings: 3,
    difficulty: 'Medium',
    spiceLevel: 'Spicy',
    ingredients: [
      RecipeIngredient(name: 'Aged Basmati Rice', quantity: 1.5, unit: 'cup'),
      RecipeIngredient(name: 'Mixed Vegetables & Paneer', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Biryani Spices (Cardamom, Mace, Cloves)', quantity: 1, unit: 'tbsp'),
      RecipeIngredient(name: 'Fried Onions (Birista) & Mint', quantity: 0.5, unit: 'cup'),
      RecipeIngredient(name: 'Saffron Milk & Ghee', quantity: 2, unit: 'tbsp'),
    ],
    equipment: ['Heavy Bottom Handi with tight lid'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Parboil basmati rice with whole spices until 70% cooked.'),
      RecipeStep(stepNumber: 2, instruction: 'Marinate vegetables in spiced curd and cook for 5 minutes in the handi.'),
      RecipeStep(stepNumber: 3, instruction: 'Layer the parboiled rice over the vegetables, top with saffron milk, fried onions, and mint. Seal and cook on dum for 15 minutes.'),
    ],
    costEstimateInr: 150.0,
    nutrition: NutritionInfo(calories: 360, proteinG: 11.0, carbsG: 56.0, fatG: 11.5, fiberG: 4.0),
    dietaryTags: ['Vegetarian', 'Random Surprise', 'Celebration', 'Chef Special'],
    allergyWarnings: ['Contains Dairy'],
    isCurated: true,
  ),
];
