import 'recipe.dart';

final List<Recipe> mockRecipes = [
  const Recipe(
    id: 'curated-1',
    dishName: 'Paneer Butter Masala',
    description: 'A rich, creamy, and mildly sweet North Indian curry made with cottage cheese in tomato-butter gravy.',
    cuisine: 'North Indian',
    mealCategory: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    totalTimeMinutes: 40,
    servings: 2,
    difficulty: 'Medium',
    spiceLevel: 'Mild',
    ingredients: [
      RecipeIngredient(name: 'Paneer (Cubes)', quantity: 200, unit: 'g'),
      RecipeIngredient(name: 'Ripe Tomatoes', quantity: 4, unit: 'piece'),
      RecipeIngredient(name: 'Butter', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Fresh Cream', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Ginger-Garlic Paste', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Kasuri Methi', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Garam Masala', quantity: 0.5, unit: 'tsp'),
      RecipeIngredient(name: 'Kashmiri Red Chilli Powder', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Kadhai or Pan', 'Blender'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Roughly chop tomatoes and blend into a smooth puree.'),
      RecipeStep(stepNumber: 2, instruction: 'Melt butter in a kadhai on medium heat, add ginger-garlic paste and sauté for 1 minute.'),
      RecipeStep(stepNumber: 3, instruction: 'Add tomato puree, Kashmiri chilli powder, and salt. Cook until butter separates.'),
      RecipeStep(stepNumber: 4, instruction: 'Add paneer cubes and simmer gently for 4 minutes with cream and crushed kasuri methi.'),
    ],
    costEstimateInr: 160.0,
    nutrition: NutritionInfo(calories: 380, proteinG: 14.5, carbsG: 12.0, fatG: 30.0, fiberG: 3.2),
    dietaryTags: ['Vegetarian', 'High Protein'],
    allergyWarnings: ['Contains Dairy'],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-2',
    dishName: 'South Indian Tomato Rasam',
    description: 'Tangy and comforting pepper-cumin soup infused with tempered curry leaves and crushed garlic.',
    cuisine: 'South Indian',
    mealCategory: 'Lunch',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 3,
    difficulty: 'Easy',
    spiceLevel: 'Spicy',
    ingredients: [
      RecipeIngredient(name: 'Tomatoes', quantity: 3, unit: 'piece'),
      RecipeIngredient(name: 'Tamarind Pulp', quantity: 1, unit: 'tbsp'),
      RecipeIngredient(name: 'Black Pepper & Cumin powder', quantity: 1.5, unit: 'tsp'),
      RecipeIngredient(name: 'Garlic cloves', quantity: 4, unit: 'piece'),
      RecipeIngredient(name: 'Mustard seeds & Curry leaves', quantity: 1, unit: 'tsp'),
      RecipeIngredient(name: 'Ghee or Oil', quantity: 1, unit: 'tsp'),
    ],
    equipment: ['Rasam pot / saucepan'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Mash boiled tomatoes with tamarind water, turmeric, and salt.'),
      RecipeStep(stepNumber: 2, instruction: 'Simmer the broth until froth forms on top.'),
      RecipeStep(stepNumber: 3, instruction: 'Temper mustard, curry leaves, and crushed garlic in ghee, then pour over the rasam.'),
    ],
    costEstimateInr: 45.0,
    nutrition: NutritionInfo(calories: 65, proteinG: 1.8, carbsG: 9.0, fatG: 2.5, fiberG: 2.0),
    dietaryTags: ['Vegetarian', 'Vegan Option', 'Immunity Booster'],
    allergyWarnings: [],
    isCurated: true,
  ),
  const Recipe(
    id: 'curated-3',
    dishName: 'Poha (Kanda Batata Poha)',
    description: 'Popular Maharashtrian breakfast made of flattened rice tempered with mustard, peanuts, and turmeric.',
    cuisine: 'Maharashtrian',
    mealCategory: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    totalTimeMinutes: 22,
    servings: 2,
    difficulty: 'Easy',
    spiceLevel: 'Medium',
    ingredients: [
      RecipeIngredient(name: 'Thick Poha (Flattened Rice)', quantity: 2, unit: 'cup'),
      RecipeIngredient(name: 'Onion (finely chopped)', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Potato (cubed small)', quantity: 1, unit: 'piece'),
      RecipeIngredient(name: 'Roasted Peanuts', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Green Chillies & Curry Leaves', quantity: 2, unit: 'piece'),
      RecipeIngredient(name: 'Lemon Juice', quantity: 1, unit: 'tbsp'),
    ],
    equipment: ['Pan', 'Strainer/Colander'],
    instructions: [
      RecipeStep(stepNumber: 1, instruction: 'Rinse poha in a colander and drain completely with a pinch of turmeric and salt.'),
      RecipeStep(stepNumber: 2, instruction: 'Heat oil, fry peanuts and potatoes until tender. Add onions and green chillies.'),
      RecipeStep(stepNumber: 3, instruction: 'Fold in the softened poha, cover and steam on low for 2 minutes. Garnish with lemon juice.'),
    ],
    costEstimateInr: 50.0,
    nutrition: NutritionInfo(calories: 220, proteinG: 5.5, carbsG: 38.0, fatG: 6.0, fiberG: 3.5),
    dietaryTags: ['Vegetarian', 'Vegan', 'Quick Breakfast'],
    allergyWarnings: ['Contains Peanuts'],
    isCurated: true,
  ),
];
